name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        export GOOS=windows
        go get -v -t -d ./...

    - name: Build
      run: |
        export GOOS=windows
        go build -v -o simple-ntlm-proxy.exe .

    - uses: actions/upload-artifact@master
      with:
        name: release
        path: simple-ntlm-proxy.exe
        
    - name: Release
      uses: docker://softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: simple-ntlm-proxy.exe
